# Generated by Django 6.0.4 on 2026-04-14 00:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_passwordresettoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('junior_developer', 'Junior Developer'), ('marketing_graduate', 'Marketing Graduate'), ('finance_analyst', 'Finance Analyst'), ('nursing', 'Nursing'), ('general', 'General')], max_length=50)),
                ('interview_type', models.CharField(choices=[('behavioural', 'Behavioural'), ('technical', 'Technical'), ('mixed', 'Mixed')], max_length=20)),
                ('experience_level', models.CharField(choices=[('junior', 'Junior'), ('mid', 'Mid-level'), ('senior', 'Senior')], max_length=20)),
                ('input_mode', models.CharField(choices=[('text', 'Text'), ('voice', 'Voice')], max_length=10)),
                ('question_count', models.IntegerField(default=5)),
                ('overall_score', models.FloatField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_number', models.IntegerField()),
                ('question_text', models.TextField()),
                ('answer_text', models.TextField(blank=True)),
                ('clarity_score', models.IntegerField(blank=True, null=True)),
                ('relevance_score', models.IntegerField(blank=True, null=True)),
                ('depth_score', models.IntegerField(blank=True, null=True)),
                ('feedback_tip', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='api.session')),
            ],
            options={
                'ordering': ['question_number'],
            },
        ),
    ]
