# Generated by Django 6.0.4 on 2026-04-14 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_session_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='experience_level',
            field=models.CharField(blank=True, choices=[('junior', 'Junior'), ('mid', 'Mid-level'), ('senior', 'Senior')], default='junior', max_length=20),
        ),
    ]
